// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-9bj6K0M1q6_N_bfwajicG4SRhbciDO0',
    appId: '1:851659979459:web:3db7afcd13dbc978d80076',
    messagingSenderId: '851659979459',
    projectId: 'automated-researcher-8bbad',
    authDomain: 'automated-researcher-8bbad.firebaseapp.com',
    storageBucket: 'automated-researcher-8bbad.firebasestorage.app',
    measurementId: 'G-HVXV2FWT85',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9bj6K0M1q6_N_bfwajicG4SRhbciDO0',
    appId: '1:851659979459:web:40a768e460546d05d80076',
    messagingSenderId: '851659979459',
    projectId: 'automated-researcher-8bbad',
    authDomain: 'automated-researcher-8bbad.firebaseapp.com',
    storageBucket: 'automated-researcher-8bbad.firebasestorage.app',
    measurementId: 'G-9H3EQ8WEV6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugqHgQef6oSVMHy3HBD-AARHAZ7oBEPc',
    appId: '1:851659979459:ios:2764157e5313549fd80076',
    messagingSenderId: '851659979459',
    projectId: 'automated-researcher-8bbad',
    storageBucket: 'automated-researcher-8bbad.firebasestorage.app',
    androidClientId: '851659979459-f9d7f5m75012ns8ocs6j1tdk6f01boc1.apps.googleusercontent.com',
    iosClientId: '851659979459-ebe86l27jrn34gh6kukfcapu45hah7p5.apps.googleusercontent.com',
    iosBundleId: 'com.crucio.automated_researcher',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugqHgQef6oSVMHy3HBD-AARHAZ7oBEPc',
    appId: '1:851659979459:ios:2764157e5313549fd80076',
    messagingSenderId: '851659979459',
    projectId: 'automated-researcher-8bbad',
    storageBucket: 'automated-researcher-8bbad.firebasestorage.app',
    androidClientId: '851659979459-f9d7f5m75012ns8ocs6j1tdk6f01boc1.apps.googleusercontent.com',
    iosClientId: '851659979459-ebe86l27jrn34gh6kukfcapu45hah7p5.apps.googleusercontent.com',
    iosBundleId: 'com.crucio.automated_researcher',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2j1tcjK8gIoiLDDySSYUmDueiH_rOAM',
    appId: '1:851659979459:android:2b68d262c42f0e74d80076',
    messagingSenderId: '851659979459',
    projectId: 'automated-researcher-8bbad',
    storageBucket: 'automated-researcher-8bbad.firebasestorage.app',
  );

}